### ISSUE TITLE
Load-testing approach, first test/attempt

### ISSUE THREAD

**Issue by stephendonner** [mozilla-services/stubattribution-loadtests#2]
1. Use https://github.com/loads/molotov
2. Write a simple test against (Bouncer? The stub attribution server?) using the Python 3 asyncio library, like so: https://github.com/rpappalax/shavar-loadtests/blob/f550099cab139cc0a760dcec920c802f675e9951/loadtest.py
3. For #2, ensure:
  * separate HMAC_KEY for this test (w/help from @oremj and @pmac)
  * safely abstracted (i.e. no keys in test code)
4. Ensure the following:
  * auth works
  * we can get and follow the response (HTTP 302?)
  * verify that we get a success/200 OK response from (stub attribution server?)

**Comment by tarekziade** [comment]
For the HMAC part, from our conversation on IRC, we can steal the HMAC signing from  https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/views.py#L153-L161 and include it in the test. 
In the interim, I am adding a call so we can focus on the rest

**Comment by pmac** [comment]
@tarekziade I pushed to master what I think will work for a test. I know you said to use `setup()` for signing but I didn't see any examples of its use, so I just have a function that gives me random code string and a signature. Take a look when you get a minute and let me know if I've done something wrong. I think it's at least a good start and ready for a try soon.

**Comment by stephendonner** [comment]
Done in many commits, finished later in https://github.com/mozilla-services/stubattribution-loadtests/commit/3b341a109687be86c1a89906d8052ffedd3502d4
